# =============================================================================
# MegooCI — development & operations Makefile
#
# Usage:
#   make              show this help
#   make up           start production stack
#   make dev          start development stack (hot-reload)
#   make logs         tail logs from the production stack
#
# On Windows, run via Git Bash, WSL, or install GNU Make:
#   choco install make        (Chocolatey)
#   scoop install make        (Scoop)
# =============================================================================

# --- Configuration ----------------------------------------------------------

COMPOSE       := docker compose
COMPOSE_PROD  := $(COMPOSE) -f docker-compose.yml
COMPOSE_DEV   := $(COMPOSE) -f docker-compose.yml -f docker-compose.dev.yml

BACKEND_SVC   := backend
FRONTEND_SVC  := frontend
DB_SVC        := db
REDIS_SVC     := redis

DB_USER       ?= megooci
DB_NAME       ?= megooci

# --- Go agent configuration --------------------------------------------------
#
# The root Makefile owns only *system-level* agent targets: building the
# Docker image and starting / stopping / tailing the agent container wired to
# the running Compose stack. Go-workflow targets (build, test, vet, fmt,
# tidy, goreleaser snapshot, clean) live in `agent/Makefile` — run those
# from inside the `agent/` directory.
AGENT_DIR            := ./agent
AGENT_VERSION        ?= 0.1.0-dev
AGENT_COMMIT         := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
AGENT_DATE           := $(shell date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)
AGENT_IMAGE          ?= megooci/agent
AGENT_IMAGE_TAG      ?= $(AGENT_VERSION)
AGENT_IMAGE_FULL     := $(AGENT_IMAGE):$(AGENT_IMAGE_TAG)
AGENT_IMAGE_LATEST   := $(AGENT_IMAGE):latest

# Runtime options for `make agent-up`. All are `?=` overridable on the
# make command line, e.g.:
#   make agent-up ID=... TOKEN=... CAPACITY=4 CONTROLLER=https://...
AGENT_CONTAINER_NAME ?= megooci-agent
# Default network matches Compose's implicit network name when the stack is
# brought up from this directory (`megooci_default`). Override with
# NETWORK=<name> if you use a non-default COMPOSE_PROJECT_NAME.
AGENT_NETWORK        ?= megooci_default
# Inside the compose network the controller is reachable as `backend:8000`.
# When running the agent on a remote host, override with CONTROLLER=https://...
AGENT_CONTROLLER     ?= http://backend:8000
AGENT_CAPACITY       ?= 2
AGENT_LOG_LEVEL      ?= info

.DEFAULT_GOAL := help

# =============================================================================
# Help — rendered via Make's $(info ...) so it works identically on
# Linux, macOS, and Windows cmd.exe without shell-specific quoting.
# =============================================================================
define HELP_TEXT

MegooCI Makefile - available targets:

  Environment
    init              Copy .env.example to .env (if missing)

  Production
    up                Build & start the production stack (detached)
    start             Start the production stack without rebuilding
    down              Stop & remove containers (keeps volumes)
    restart           Restart all production services
    build             Rebuild production images
    pull              Pull latest base images
    logs              Tail logs from the production stack
    ps                List running production containers

  Development
    dev               Build & start the dev stack in the foreground
    dev-up            Start the dev stack in the background
    dev-down          Stop & remove dev containers
    dev-restart       Restart all dev services
    dev-build         Rebuild dev images
    dev-logs          Tail logs from the dev stack
    dev-ps            List running dev containers

  Shells & Debugging
    shell             Bash shell in the backend container
    frontend-shell    Shell in the frontend container
    db-shell          psql session in the Postgres container
    redis-shell       redis-cli in the Redis container
    logs-backend      Tail backend logs only
    logs-frontend     Tail frontend logs only
    logs-celery       Tail celery worker + beat logs

  Database
    migrate                    Run alembic upgrade head
    migration m="msg"          Create a new autogenerated migration
    migrate-down               Roll back the most recent migration

  Agent (megooci-agent, PRD F-3.4)
    agent-image                Build the agent Docker image
    agent-image-push           Push the image to the configured registry
    agent-up ID=.. TOKEN=..    Run the agent container, passing ID and token as
                                 CLI flags to `docker run`. Extra overrides:
                                   CONTROLLER=<url> CAPACITY=<n> LOG_LEVEL=<lvl>
                                   NETWORK=<name>   NAME=<container-name>
    agent-down                 Stop & remove the agent container
    agent-restart              Restart the agent container (keeps its config)
    agent-logs                 Tail agent container logs
    agent-shell                Open a shell inside the running agent container
    (Go developer workflow: `cd agent && make build|test|vet|fmt|tidy|snapshot|clean`)

  Cleanup
    clean             Stop stack & remove orphan containers
    nuke CONFIRM=yes  Stop stack AND delete all volumes (DESTRUCTIVE!)
    prune             Remove dangling Docker images & build cache

endef
export HELP_TEXT

.PHONY: help
help: ## Show this help message
	$(info $(HELP_TEXT))
	@:

# =============================================================================
# Environment
# =============================================================================
.PHONY: init
init: ## Copy .env.example → .env (only if .env does not exist)
	@if [ ! -f .env ]; then \
		cp .env.example .env && echo "Created .env from .env.example — edit it before first run."; \
	else \
		echo ".env already exists — not overwriting."; \
	fi

# =============================================================================
# Production
# =============================================================================
.PHONY: up
up: ## Build & start the production stack in the background
	$(COMPOSE_PROD) up -d --build

.PHONY: start
start: ## Start the production stack (no rebuild)
	$(COMPOSE_PROD) up -d

.PHONY: down
down: ## Stop & remove containers (keeps volumes)
	$(COMPOSE_PROD) down

.PHONY: restart
restart: ## Restart all production services
	$(COMPOSE_PROD) restart

.PHONY: build
build: ## Rebuild production images
	$(COMPOSE_PROD) build

.PHONY: pull
pull: ## Pull latest base images
	$(COMPOSE_PROD) pull

.PHONY: logs
logs: ## Tail logs from the production stack (Ctrl+C to stop)
	$(COMPOSE_PROD) logs -f --tail=200

.PHONY: ps
ps: ## List running production containers
	$(COMPOSE_PROD) ps

# =============================================================================
# Development
# =============================================================================
.PHONY: dev
dev: ## Build & start the dev stack (bind-mounted, hot-reload)
	$(COMPOSE_DEV) up --build

.PHONY: dev-up
dev-up: ## Start the dev stack in the background
	$(COMPOSE_DEV) up -d --build

.PHONY: dev-down
dev-down: ## Stop & remove dev containers (keeps volumes)
	$(COMPOSE_DEV) down

.PHONY: dev-restart
dev-restart: ## Restart all dev services
	$(COMPOSE_DEV) restart

.PHONY: dev-build
dev-build: ## Rebuild dev images
	$(COMPOSE_DEV) build

.PHONY: dev-logs
dev-logs: ## Tail logs from the dev stack
	$(COMPOSE_DEV) logs -f --tail=200

.PHONY: dev-ps
dev-ps: ## List running dev containers
	$(COMPOSE_DEV) ps

# =============================================================================
# Shells & Debugging
# =============================================================================
.PHONY: shell
shell: ## Open a bash shell in the backend container
	$(COMPOSE_DEV) exec $(BACKEND_SVC) /bin/bash

.PHONY: frontend-shell
frontend-shell: ## Open a shell in the frontend container
	$(COMPOSE_DEV) exec $(FRONTEND_SVC) /bin/sh

.PHONY: db-shell
db-shell: ## Open a psql session in the Postgres container
	$(COMPOSE_DEV) exec $(DB_SVC) psql -U $(DB_USER) -d $(DB_NAME)

.PHONY: redis-shell
redis-shell: ## Open a redis-cli session in the Redis container
	$(COMPOSE_DEV) exec $(REDIS_SVC) redis-cli

.PHONY: logs-backend
logs-backend: ## Tail backend logs only
	$(COMPOSE_DEV) logs -f --tail=200 $(BACKEND_SVC)

.PHONY: logs-frontend
logs-frontend: ## Tail frontend logs only
	$(COMPOSE_DEV) logs -f --tail=200 $(FRONTEND_SVC)

.PHONY: logs-celery
logs-celery: ## Tail celery worker + beat logs
	$(COMPOSE_DEV) logs -f --tail=200 celery-worker celery-beat

# =============================================================================
# Database
# =============================================================================
.PHONY: migrate
migrate: ## Run database migrations (alembic upgrade head)
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic upgrade head

.PHONY: migration
migration: ## Create a new migration. Usage: make migration m="add users table"
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic revision --autogenerate -m "$(m)"

.PHONY: migrate-down
migrate-down: ## Roll back the most recent migration
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic downgrade -1

# =============================================================================
# Agent (megooci-agent — Docker image + container lifecycle)
# =============================================================================
#
# These targets glue the agent to the rest of the running stack. For pure Go
# workflows (build / test / vet / fmt / tidy / goreleaser snapshot / clean)
# use `agent/Makefile` instead:
#
#     cd agent && make build
#     cd agent && make test
#
# Typical operator flow:
#
#   1. make agent-image                    (one-off: build the Docker image)
#   2. Register the agent in the MegooCI UI and copy its ID + token.
#   3. make agent-up ID=<uuid> TOKEN=<token>
#      (ID + token are passed as CLI flags to `docker run`, never persisted)
#   4. make agent-logs                     (verify it connected)
#
# -----------------------------------------------------------------------------
#
# Runtime overrides (all passable as make variables to `agent-up`):
#
#   ID             required — agent UUID from the UI
#   TOKEN          required — one-shot registration / rotate token
#   CONTROLLER     default $(AGENT_CONTROLLER)
#   CAPACITY       default $(AGENT_CAPACITY)
#   LOG_LEVEL      default $(AGENT_LOG_LEVEL)
#   NETWORK        default $(AGENT_NETWORK) (must match your Compose project)
#   NAME           default $(AGENT_CONTAINER_NAME)
#
# -----------------------------------------------------------------------------

# Internal: effective values with defaults. Users set ID, TOKEN, etc. on the
# make command line; $(or ...) falls back to the build-time defaults above.
_AGENT_ID            := $(ID)
_AGENT_TOKEN         := $(TOKEN)
_AGENT_CONTROLLER    := $(or $(CONTROLLER),$(AGENT_CONTROLLER))
_AGENT_CAPACITY      := $(or $(CAPACITY),$(AGENT_CAPACITY))
_AGENT_LOG_LEVEL     := $(or $(LOG_LEVEL),$(AGENT_LOG_LEVEL))
_AGENT_NETWORK       := $(or $(NETWORK),$(AGENT_NETWORK))
_AGENT_NAME          := $(or $(NAME),$(AGENT_CONTAINER_NAME))

.PHONY: agent-image
agent-image: ## Build the agent Docker image (tags: $(AGENT_IMAGE_FULL) + latest)
	docker build \
		--build-arg VERSION=$(AGENT_VERSION) \
		--build-arg COMMIT=$(AGENT_COMMIT) \
		--build-arg DATE=$(AGENT_DATE) \
		-t $(AGENT_IMAGE_FULL) \
		-t $(AGENT_IMAGE_LATEST) \
		$(AGENT_DIR)
	@echo "Built image: $(AGENT_IMAGE_FULL)"
	@echo "             $(AGENT_IMAGE_LATEST)"

.PHONY: agent-image-push
agent-image-push: ## Push the agent image to a registry ($(AGENT_IMAGE))
	docker push $(AGENT_IMAGE_FULL)
	docker push $(AGENT_IMAGE_LATEST)

.PHONY: agent-up
agent-up: ## Run the agent container. Usage: make agent-up ID=<uuid> TOKEN=<token>
	@if [ -z "$(_AGENT_ID)" ] || [ -z "$(_AGENT_TOKEN)" ]; then \
		echo "ERROR: ID and TOKEN are required."; \
		echo ""; \
		echo "Usage: make agent-up ID=<uuid> TOKEN=<megci_agt_...>"; \
		echo ""; \
		echo "Optional overrides:"; \
		echo "  CONTROLLER=$(_AGENT_CONTROLLER)  (use a public URL when running off-host)"; \
		echo "  CAPACITY=$(_AGENT_CAPACITY)"; \
		echo "  LOG_LEVEL=$(_AGENT_LOG_LEVEL)"; \
		echo "  NETWORK=$(_AGENT_NETWORK)         (must match your docker compose project)"; \
		echo "  NAME=$(_AGENT_NAME)"; \
		exit 1; \
	fi
	@docker rm -f $(_AGENT_NAME) >/dev/null 2>&1 || true
	docker run -d \
		--name $(_AGENT_NAME) \
		--restart unless-stopped \
		--network $(_AGENT_NETWORK) \
		$(AGENT_IMAGE_LATEST) \
		run \
			--controller $(_AGENT_CONTROLLER) \
			--agent-id $(_AGENT_ID) \
			--token $(_AGENT_TOKEN) \
			--capacity $(_AGENT_CAPACITY) \
			--log-level $(_AGENT_LOG_LEVEL)
	@echo "Agent started as container '$(_AGENT_NAME)'. Tail logs with: make agent-logs"

.PHONY: agent-down
agent-down: ## Stop & remove the agent container
	@docker rm -f $(_AGENT_NAME) >/dev/null 2>&1 && echo "Removed container $(_AGENT_NAME)" || echo "Container $(_AGENT_NAME) not running."

.PHONY: agent-restart
agent-restart: ## Restart the agent container (keeps its original CLI args)
	docker restart $(_AGENT_NAME)

.PHONY: agent-logs
agent-logs: ## Tail agent container logs
	docker logs -f --tail=200 $(_AGENT_NAME)

.PHONY: agent-shell
agent-shell: ## Open a shell in the running agent container
	docker exec -it $(_AGENT_NAME) /bin/sh

# =============================================================================
# Cleanup
# =============================================================================
.PHONY: clean
clean: ## Stop stack and remove orphan containers (keeps volumes)
	$(COMPOSE_DEV) down --remove-orphans

.PHONY: nuke
nuke: ## Stop stack AND delete all named volumes (DESTROYS DB + artifacts!)
	@echo "WARNING: This will delete Postgres data, Redis data, and all MegooCI storage."
	@echo "         Re-run with CONFIRM=yes to proceed, e.g. 'make nuke CONFIRM=yes'."
ifeq ($(CONFIRM),yes)
	$(COMPOSE_DEV) down -v --remove-orphans
	@echo "All volumes removed."
else
	@echo "Aborted (CONFIRM not set to 'yes')."
endif

.PHONY: prune
prune: ## Remove dangling Docker images and build cache
	docker image prune -f
	docker builder prune -f
