# =============================================================================
# MegooCI — development & operations Makefile
#
# Usage:
#   make              show this help
#   make up           start production stack
#   make dev          start development stack (hot-reload)
#   make logs         tail logs from the production stack
#
# On Windows, run via Git Bash, WSL, or install GNU Make:
#   choco install make        (Chocolatey)
#   scoop install make        (Scoop)
# =============================================================================

# --- Configuration ----------------------------------------------------------

COMPOSE       := docker compose
COMPOSE_PROD  := $(COMPOSE) -f docker-compose.yml
COMPOSE_DEV   := $(COMPOSE) -f docker-compose.yml -f docker-compose.dev.yml

BACKEND_SVC   := backend
FRONTEND_SVC  := frontend
DB_SVC        := db
REDIS_SVC     := redis

DB_USER       ?= megooci
DB_NAME       ?= megooci

.DEFAULT_GOAL := help

# =============================================================================
# Help — rendered via Make's $(info ...) so it works identically on
# Linux, macOS, and Windows cmd.exe without shell-specific quoting.
# =============================================================================
define HELP_TEXT

MegooCI Makefile - available targets:

  Environment
    init              Copy .env.example to .env (if missing)

  Production
    up                Build & start the production stack (detached)
    start             Start the production stack without rebuilding
    down              Stop & remove containers (keeps volumes)
    restart           Restart all production services
    build             Rebuild production images
    pull              Pull latest base images
    logs              Tail logs from the production stack
    ps                List running production containers

  Development
    dev               Build & start the dev stack in the foreground
    dev-up            Start the dev stack in the background
    dev-down          Stop & remove dev containers
    dev-restart       Restart all dev services
    dev-build         Rebuild dev images
    dev-logs          Tail logs from the dev stack
    dev-ps            List running dev containers

  Shells & Debugging
    shell             Bash shell in the backend container
    frontend-shell    Shell in the frontend container
    db-shell          psql session in the Postgres container
    redis-shell       redis-cli in the Redis container
    logs-backend      Tail backend logs only
    logs-frontend     Tail frontend logs only
    logs-celery       Tail celery worker + beat logs

  Database
    migrate                    Run alembic upgrade head
    migration m="msg"          Create a new autogenerated migration
    migrate-down               Roll back the most recent migration

  Cleanup
    clean             Stop stack & remove orphan containers
    nuke CONFIRM=yes  Stop stack AND delete all volumes (DESTRUCTIVE!)
    prune             Remove dangling Docker images & build cache

endef
export HELP_TEXT

.PHONY: help
help: ## Show this help message
	$(info $(HELP_TEXT))
	@:

# =============================================================================
# Environment
# =============================================================================
.PHONY: init
init: ## Copy .env.example → .env (only if .env does not exist)
	@if [ ! -f .env ]; then \
		cp .env.example .env && echo "Created .env from .env.example — edit it before first run."; \
	else \
		echo ".env already exists — not overwriting."; \
	fi

# =============================================================================
# Production
# =============================================================================
.PHONY: up
up: ## Build & start the production stack in the background
	$(COMPOSE_PROD) up -d --build

.PHONY: start
start: ## Start the production stack (no rebuild)
	$(COMPOSE_PROD) up -d

.PHONY: down
down: ## Stop & remove containers (keeps volumes)
	$(COMPOSE_PROD) down

.PHONY: restart
restart: ## Restart all production services
	$(COMPOSE_PROD) restart

.PHONY: build
build: ## Rebuild production images
	$(COMPOSE_PROD) build

.PHONY: pull
pull: ## Pull latest base images
	$(COMPOSE_PROD) pull

.PHONY: logs
logs: ## Tail logs from the production stack (Ctrl+C to stop)
	$(COMPOSE_PROD) logs -f --tail=200

.PHONY: ps
ps: ## List running production containers
	$(COMPOSE_PROD) ps

# =============================================================================
# Development
# =============================================================================
.PHONY: dev
dev: ## Build & start the dev stack (bind-mounted, hot-reload)
	$(COMPOSE_DEV) up --build

.PHONY: dev-up
dev-up: ## Start the dev stack in the background
	$(COMPOSE_DEV) up -d --build

.PHONY: dev-down
dev-down: ## Stop & remove dev containers (keeps volumes)
	$(COMPOSE_DEV) down

.PHONY: dev-restart
dev-restart: ## Restart all dev services
	$(COMPOSE_DEV) restart

.PHONY: dev-build
dev-build: ## Rebuild dev images
	$(COMPOSE_DEV) build

.PHONY: dev-logs
dev-logs: ## Tail logs from the dev stack
	$(COMPOSE_DEV) logs -f --tail=200

.PHONY: dev-ps
dev-ps: ## List running dev containers
	$(COMPOSE_DEV) ps

# =============================================================================
# Shells & Debugging
# =============================================================================
.PHONY: shell
shell: ## Open a bash shell in the backend container
	$(COMPOSE_DEV) exec $(BACKEND_SVC) /bin/bash

.PHONY: frontend-shell
frontend-shell: ## Open a shell in the frontend container
	$(COMPOSE_DEV) exec $(FRONTEND_SVC) /bin/sh

.PHONY: db-shell
db-shell: ## Open a psql session in the Postgres container
	$(COMPOSE_DEV) exec $(DB_SVC) psql -U $(DB_USER) -d $(DB_NAME)

.PHONY: redis-shell
redis-shell: ## Open a redis-cli session in the Redis container
	$(COMPOSE_DEV) exec $(REDIS_SVC) redis-cli

.PHONY: logs-backend
logs-backend: ## Tail backend logs only
	$(COMPOSE_DEV) logs -f --tail=200 $(BACKEND_SVC)

.PHONY: logs-frontend
logs-frontend: ## Tail frontend logs only
	$(COMPOSE_DEV) logs -f --tail=200 $(FRONTEND_SVC)

.PHONY: logs-celery
logs-celery: ## Tail celery worker + beat logs
	$(COMPOSE_DEV) logs -f --tail=200 celery-worker celery-beat

# =============================================================================
# Database
# =============================================================================
.PHONY: migrate
migrate: ## Run database migrations (alembic upgrade head)
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic upgrade head

.PHONY: migration
migration: ## Create a new migration. Usage: make migration m="add users table"
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic revision --autogenerate -m "$(m)"

.PHONY: migrate-down
migrate-down: ## Roll back the most recent migration
	$(COMPOSE_DEV) exec $(BACKEND_SVC) alembic downgrade -1

# =============================================================================
# Cleanup
# =============================================================================
.PHONY: clean
clean: ## Stop stack and remove orphan containers (keeps volumes)
	$(COMPOSE_DEV) down --remove-orphans

.PHONY: nuke
nuke: ## Stop stack AND delete all named volumes (DESTROYS DB + artifacts!)
	@echo "WARNING: This will delete Postgres data, Redis data, and all MegooCI storage."
	@echo "         Re-run with CONFIRM=yes to proceed, e.g. 'make nuke CONFIRM=yes'."
ifeq ($(CONFIRM),yes)
	$(COMPOSE_DEV) down -v --remove-orphans
	@echo "All volumes removed."
else
	@echo "Aborted (CONFIRM not set to 'yes')."
endif

.PHONY: prune
prune: ## Remove dangling Docker images and build cache
	docker image prune -f
	docker builder prune -f
